services:
  radarr4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr4k
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /media/big1/media4k:/media4k
      - /media/big2/media4k:/media4k2
      - /media/big1/downloads:/downloads
    ports:
      - 7879:7878
    hostname: radarr4k
    networks:
      - qbt-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr4k.tls=${TLS_ENABLED}"
      - "traefik.http.routers.radarr4k.entrypoints=${WEB_ENTRYPOINT}"
      - "traefik.http.routers.radarr4k.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr4k.rule=Host(`${DOMAIN}`) && PathPrefix(`/radarr4k`)"
      - "traefik.http.services.radarr4k.loadbalancer.server.port=7878"

networks:
  qbt-network:
    external: true
