services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr 
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Bucharest
    volumes:
      - /data/sonarr/config:/config
      - /media/big1/media:/media
      - /media/big2/media:/media2
      - /media/big2/shared:/shared
      - /media/big1/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - qbt-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.tls={TLS_ENABLED}"
      - "traefik.http.routers.sonarr.entrypoints=${WEB_ENTRYPOINT}"
      - "traefik.http.routers.sonarr.rule=Host(`${DOMAIN}`) && PathPrefix(`/sonarr`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"

networks:
  qbt-network:
    external: true
