services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      - qbt-network
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6882
    volumes:
      - ./config:/config
      - /media/big1/downloads:/downloads
    ports:
      - 8080:8080
      - 6882:6882
      - 6882:6882/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.tls={TLS_ENABLED}"
      - "traefik.http.routers.qbittorrent.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.entrypoints=${WEB_ENTRYPOINT}"
      - "traefik.http.routers.qbittorrent.tls.certresolver=myresolver"

networks:
  qbt-network:
    external: true
