services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Bucharest #optional
      - SUBDOMAINS=calibreweb-my,emby-my,portainer-my,qbt-my,qbtbox
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - ./config:/config #optional
    restart: unless-stopped
