services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    networks:
      - qbt-network
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./config:/config
      - /media/big1/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.entrypoints=websecure"
      - "traefik.http.routers.deluge.rule=Host(`qbt-my.duckdns.org`)"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
      - "traefik.http.routers.deluge.tls=true"
      - "traefik.http.routers.deluge.tls.certresolver=lets-encr"

networks:
  qbt-network:
    external: true
