services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - /data/radarr/config:/config
      - /media/big/media:/media
      - /media/big/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - qbt-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.rule=Host(`qbt-my.duckdns.org`) && PathPrefix(`/radarr`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=lets-encr"

networks:
  qbt-network:
    external: true
