services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - qbt-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Bucharest
      - WATCHTOWER_SCHEDULE=0 30 5 * * *
    command: --cleanup --debug
    restart: unless-stopped

networks:
  qbt-network:
    external: true
