services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest 
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - qbt-network
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Bucharest
    volumes:
      - /data/jellyfin/cache:/cache
      - /data/jellyfin/config:/config
      - /media/big/media:/media
      - /media/big/media4k:/media4k
      - /media/big/downloads:/downloads
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu, utility, video]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`emby-my.duckdns.org`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=lets-encr"

networks:
  qbt-network:
    external: true
