services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Bucharest
    volumes:
      - ./config:/config
      - /media/big1/media:/media
      - /media/big1/downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - qbt-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.tls=${TLS_ENABLED}"
      - "traefik.http.routers.bazarr.entrypoints=${WEB_ENTRYPOINT}"
      - "traefik.http.routers.bazarr.tls.certresolver=myresolver"
      - "traefik.http.routers.bazarr.rule=Host(`${DOMAIN}`) && PathPrefix(`/bazarr`)"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"

networks:
  qbt-network:
    external: true
