services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: mediabox-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/big2/syncthing:/var/syncthing
      - /media/big2/books:/books
    networks:
      - qbt-network
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.tls=${TLS_ENABLED}"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${DOMAIN}`)"
      - "traefik.http.routers.syncthing.entrypoints=${WEB_ENTRYPOINT}"
      - "traefik.http.routers.syncthing.tls.certresolver=myresolver"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"


networks:
  qbt-network:
    external: true
